In [2]:
import pandas as pd
import numpy as np
import scipy.stats as sci 
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score


In [3]:
df = pd.read_csv(r"D:\#10\AI\CA4\house_data.csv")
df.info()
df['sqft_living'] = df['sqft_living'].fillna(df['sqft_living'].mode()[0])
df['floors'] = df['floors'].fillna(df['floors'].mode()[0])
df['sqft_basement'] = df['sqft_basement'].fillna(df['sqft_basement'].mode()[0])
df['yr_built'] = df['yr_built'].fillna(df['yr_built'].mode()[0])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 27 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Unnamed: 0.2   21613 non-null  int64  
 1   Unnamed: 0.1   21613 non-null  int64  
 2   Unnamed: 0     21613 non-null  int64  
 3   id             21613 non-null  int64  
 4   date           21613 non-null  object 
 5   price          21613 non-null  float64
 6   bedrooms       21613 non-null  int64  
 7   bathrooms      21613 non-null  float64
 8   sqft_living    18528 non-null  float64
 9   sqft_lot       21613 non-null  int64  
 10  floors         18530 non-null  float64
 11  waterfront     21613 non-null  int64  
 12  view           21613 non-null  int64  
 13  condition      21613 non-null  int64  
 14  grade          21613 non-null  int64  
 15  sqft_above     21613 non-null  int64  
 16  sqft_basement  21184 non-null  float64
 17  yr_built       18531 non-null  float64
 18  yr_ren

In [4]:
for i in df.columns:
    label_encoder = preprocessing.LabelEncoder()
    if df[i].dtype == 'object':
        df[i]= label_encoder.fit_transform(df[i])
        df[i].unique()
df

Unnamed: 0.2  Unnamed: 0.1  Unnamed: 0          id  date     price  \
0                 0             0           0  7129300520   164  221900.0   
1                 1             1           1  6414100192   220  538000.0   
2                 2             2           2  5631500400   290  180000.0   
3                 3             3           3  2487200875   220  604000.0   
4                 4             4           4  1954400510   283  510000.0   
...             ...           ...         ...         ...   ...       ...   
21608         21608         21608       21608   263000018    19  360000.0   
21609         21609         21609       21609  6600060120   288  400000.0   
21610         21610         21610       21610  1523300141    52  402101.0   
21611         21611         21611       21611   291310100   252  400000.0   
21612         21612         21612       21612  1523300157   166  325000.0   

       bedrooms  bathrooms  sqft_living  sqft_lot  ...  yr_built  \
0             3       1.00       1180.0      5650  ...    1955.0   
1             3       2.25       2570.0      7242  ...    2014.0   
2             2       1.00        770.0     10000  ...    1933.0   
3             4       3.00       1960.0      5000  ...    1965.0   
4             3       2.00       1680.0      8080  ...    1987.0   
...         ...        ...          ...       ...  ...       ...   
21608         3       2.50       1530.0      1131  ...    2009.0   
21609         4       2.50       2310.0      5813  ...    2014.0   
21610         2       0.75       1020.0      1350  ...    2014.0   
21611         3       2.50       1600.0      2388  ...    2004.0   
21612         2       0.75       1020.0      1076  ...    2008.0   

       yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  \
0                 0    98178  47.5112 -122.257           1340        5650   
1              1991    98125  47.7210 -122.319           1690        7639   
2                 0    98028  47.7379 -122.233           2720        8062   
3                 0    98136  47.5208 -122.393           1360        5000   
4                 0    98074  47.6168 -122.045           1800        7503   
...             ...      ...      ...      ...            ...         ...   
21608             0    98103  47.6993 -122.346           1530        1509   
21609             0    98146  47.5107 -122.362           1830        7200   
21610             0    98144  47.5944 -122.299           1020        2007   
21611             0    98027  47.5345 -122.069           1410        1287   
21612             0    98144  47.5941 -122.299           1020        1357   

       location  style  house_age  
0             1      2         67  
1             1      3         71  
2             0      4         89  
3             2      1         57  
4             1      0         35  
...         ...    ...        ...  
21608         1      4         13  
21609         1      0          8  
21610         1      3         13  
21611         0      2         18  
21612         0      3         14  

[21613 rows x 27 columns]

In [5]:
median = df['price'].median()
df['price_level'] = ['1' if x >= median else '-1' for x in df['price']]

In [6]:


X = df.drop('price_level', axis=1)
y = df['price_level']
max_depth_range = [3, 5, 7, 10, 15, 20, 25]
cv_scores = []
for max_depth in max_depth_range:
    dt = DecisionTreeRegressor(max_depth=max_depth)
    scores = cross_val_score(dt, X, y, cv=5, scoring='neg_mean_squared_error')
    cv_scores.append(scores.mean())
for i in range(len(max_depth_range)):
    print("Max depth: {}, CV score: {}".format(max_depth_range[i], cv_scores[i]))
max_score_index = cv_scores.index(max(cv_scores))
best_max_depth = max_depth_range[max_score_index]
print("Best max depth:", best_max_depth)

Max depth: 3, CV score: 0.0
Max depth: 5, CV score: 0.0
Max depth: 7, CV score: 0.0
Max depth: 10, CV score: 0.0
Max depth: 15, CV score: 0.0
Max depth: 20, CV score: 0.0
Max depth: 25, CV score: 0.0
Best max depth: 3


In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('price_level', axis=1), df['price_level'], test_size=0.2)
max_depth_range = [2, 3, 4, 5, 6]
min_samples_split_range = [2,3, 5, 10, 15, 20]
criterion_range = ['gini', 'entropy']
best_accuracy = 0
best_max_depth = None
best_min_samples_split = None
best_criterion = None
for max_depth in max_depth_range:
    for min_samples_split in min_samples_split_range:
        for criterion in criterion_range:
            clf = tree.DecisionTreeClassifier(max_depth=max_depth, min_samples_split=min_samples_split, criterion=criterion)
            clf.fit(X_train, y_train)
            y_pred_test = clf.predict(X_test)
            test_accuracy = accuracy_score(y_test, y_pred_test)
            if test_accuracy > best_accuracy:
                best_accuracy = test_accuracy
                best_max_depth = max_depth
                best_min_samples_split = min_samples_split
                best_criterion = criterion
print('Best max depth:', best_max_depth)
print('Best min samples split:', best_min_samples_split)
print('Best criterion:', best_criterion)
print('Best accuracy:', best_accuracy)
cm = confusion_matrix(y_test, y_pred_test)
print('Confusion Matrix:\n', cm)

Best max depth: 2
Best min samples split: 2
Best criterion: gini
Best accuracy: 1.0
Confusion Matrix:
 [[2095    0]
 [   0 2228]]


In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X_train, X_test, y_train, y_test = train_test_split(df.drop('price_level', axis=1), df['price_level'], test_size=0.2)
k_range = list(range(1, 10))
best_accuracy = 0
best_k = None
for k in k_range:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    y_pred_test = knn.predict(X_test)
    test_accuracy = accuracy_score(y_test, y_pred_test)
    if test_accuracy > best_accuracy:
        best_accuracy = test_accuracy
        best_k = k
cm = confusion_matrix(y_test, y_pred_test)
print('Confusion Matrix:\n', cm)
print('Best k:', best_k)
print('Best accuracy:', best_accuracy)

C:\Users\shayan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\shayan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepd

Confusion Matrix:
 [[1757  395]
 [ 463 1708]]
Best k: 1
Best accuracy: 0.8977561878325238


C:\Users\shayan\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('price_level', axis=1), df['price_level'], test_size=0.2)
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100, 1000]}
lr = LogisticRegression()
lr_cv = GridSearchCV(lr, param_grid, cv=5)
lr_cv.fit(X_train, y_train)
y_pred_test = lr_cv.predict(X_test)
cm = confusion_matrix(y_test, y_pred_test)
print('Confusion Matrix:\n', cm)
test_accuracy = accuracy_score(y_test, y_pred_test)
print('Test accuracy:', test_accuracy)

print('Optimal hyperparameters:', lr_cv.best_params_)

Confusion Matrix:
 [[1038 1095]
 [ 354 1836]]
Test accuracy: 0.6648160999306038
Optimal hyperparameters: {'C': 0.001}
